//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int ProductTypeID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<bool> InStock { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<System.DateTime> DateOnShelf { get; set; }
        public int CraftsmanID { get; set; }
    
    }
}
